### ISSUE TITLE
No posibility to select LOOPS

### ISSUE THREAD

**Issue by adrianveq** [dairin0d/blender-2.8-scripts#1]
How I can select loops, when ALT doesn't work? (zbrush preset)
It would be awesome with doubleclick, like in "emulate 3 mouse button" option.

**Comment by dairin0d** [comment]
In the ZBrush preset, Alt+Left Mouse starts the navigation in the panning mode. Making it work with Left Mouse double-click appears to be problematic.

However, I now added an option to always use the ZBrush mode (previously, it only worked when no keyboard modifiers were pressed). It's located in the "Navigation shortcuts" section of the addon's preferences.

The zip of the new version will most likely be uploaded sometime around tomorrow, but in the meantime you can try to replace the [__init__.py](https://raw.githubusercontent.com/dairin0d/blender-2.8-scripts/master/scripts/addons/mouselook_navigation/__init__.py) file manually.

After you've updated the addon, load the ZBrush preset and set ZBrush mode to Always, and it should fix your problem with Alt+Left Mouse loop selection (don't forget to save the preferences).

**Comment by dairin0d** [comment]
I changed the ZBrush preset, so now it should work out-of-the-box.
