### ISSUE TITLE
Add-on Does not work in Blender 3.0 Alpha

### ISSUE THREAD

**Issue by Cuzmix** [dairin0d/blender-2.8-scripts#10]
when trying to install the add-on on blender 3.0  the following error is returned, this happens with all versions that are not the LTS
![image](https://user-images.githubusercontent.com/24409855/129630645-22af4bf7-a08b-4868-b458-8a62986d9497.png)

**Comment by dairin0d** [comment]
Hi, sorry for taking so long to respond. Try the latest version (1.7.4), it should work in the recent Blender 3.0... unless there was another API incompatibility that got introduced in the last few days xD

**Comment by Cuzmix** [comment]
Hey No worries , thanks for the fix its working perfectly in 3.0😃  Kind regards,Manny From: dairin0dSent: 23 August 2021 19:29To: dairin0d/blender-2.8-scriptsCc: Manny; AuthorSubject: Re: [dairin0d/blender-2.8-scripts] Add-on Does not work in Blender 3.0 Alpha (#10) Hi, sorry for taking so long to respond. Try the latest version (1.7.4), it should work in the recent Blender 3.0... unless there was another API incompatibility that got introduced in the last few days xD—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
