### ISSUE TITLE
Zbrush Navigation in Grease Pencil Model

### ISSUE THREAD

**Issue by ManuelGPz** [dairin0d/blender-2.8-scripts#11]
Hello,

This might be me not using the tool as it is supposed to be used but I guess it might be worth asking here. 

I am trying to use the mouse navigation tool in Draw Mode in Grease Pencil to behave like in Zbrush so I can freely move around the scene while is active and use a shortcut ( in my case ALT + "Tilda" )  to turn the mouse navigation off when I want to draw with the Grease Pencil. 

The problem I face I the mouse navigation tool is not working for me in Grease Pencil, Draw mode. It always try to draw something. 
Is there a way to make it work there? Maybe I am doing something wrong.

Using W10 and Offical Release of Blender 3.0

Thanks so much.

**Comment by dairin0d** [comment]
Hi, I made a test version of the addon which has an additional "Grease Pencil" keymap option.
[mouselook_navigation.zip](https://github.com/dairin0d/blender-2.8-scripts/files/7775729/mouselook_navigation.zip)
![image](https://user-images.githubusercontent.com/1641842/147383380-13ccb640-911e-453a-947b-713bc561e0b9.png)
Try installing it, load the ZBrush preset, in the Keymaps drop-down (shown on the screenshot) enable the Grease Pencil option, and click the Update Keymaps button.
Let me know how it goes :-)

**Comment by ManuelGPz** [comment]
It works perfect man!

Thanks so much for the Chirstmas present!

**Comment by ManuelGPz** [comment]
I use the addon for personal use, but I left a coffee in Gumroad, I think is the least I can do.

Thanks so much for the effort and for keeping the addon alive and updated.

I hope you are having a great Christmas.

**Comment by dairin0d** [comment]
Thanks! :-)

**Comment by joebreaker** [comment]
Hey! 
Thanks for this wonderful addon!
I've been reckless enough not to remove the old version of the MouseLook Navigation. 
Now I cannot install neither of the versions(((

Could you please help me out?

it reads this:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\__init__.py", line 2400, in register
    addon.register()
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 746, in register
    self.__register_class(self.classes_new.popitem(last=False)[0])
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 724, in __register_class
    self.__register_class_annotations(cls, prop_infos)
  File "C:\Users\Professional\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mouselook_navigation\dairin0d\utils_addon.py", line 712, in __register_class_annotations
    bpy.utils.register_class(cls)
ValueError: bpy_struct "mouselook_navigation-preferences" registration error: 'raycast_modes' EnumProperty could not register (see previous error)

**Comment by dairin0d** [comment]
@joebreaker The problem you're reporting doesn't seem to be related to this issue. Please create new issues for new problems (e.g. using a "Report a Bug" button in the addon), instead of commenting on the existing ones. Just in case, I've made a new issue for your report, further discussion should be continued there: https://github.com/dairin0d/blender-2.8-scripts/issues/19
