### ISSUE TITLE
Not working on blender 3.1

### ISSUE THREAD

**Issue by supramatti** [dairin0d/blender-2.8-scripts#13]

**Comment by dairin0d** [comment]
Hi, sorry for the late reply,
What exactly isn't working? I downloaded Blender 3.1.0, and at a cursory glance both Mouselook Navigation and Cut/Copy/Paste addons seem to work as they should.

Which addon(s) were you trying to use?
Was there a problem with addon installation? When enabling an addon? When you attempted to use an addon?
What exactly happened? (describe the problem in detail)
Were there any errors in the console? (to open the console, use Blender's menu _Window -> Toggle System Console_)

**Comment by supramatti** [comment]
Hello. I'm trying to use the Mouse-look Navigation add-on. No problem at
all to install the addon.

The mouse navigation, as if it was on zbrush, isn't working. Also the
zbrush border isn't working as well. I'm using blender latest version, 3.1.2

No messages on the console.


Em dom., 3 de abr. de 2022 às 10:16, dairin0d ***@***.***>
escreveu:

**Comment by dairin0d** [comment]
Hm... Just to be certain, is this what you're seeing in the Keymaps tab of the addon's preferences?
![image](https://user-images.githubusercontent.com/1641842/161434246-36ff7018-613e-4fb8-893e-45144e0d7bb1.png)

**Comment by supramatti** [comment]
That's it! I didn't load the zbrush profile. Sorry about that, really
sorry. Now it's working greatly.

Thank you very much!!!

Em dom., 3 de abr. de 2022 às 12:03, dairin0d ***@***.***>
escreveu:

**Comment by dairin0d** [comment]
No problem. You're welcome!
