### ISSUE TITLE
laggy in Zbrush profile

### ISSUE THREAD

**Issue by visualworx** [dairin0d/blender-2.8-scripts#14]
whenever I try to navigate in Zbrush mode there's a moment that calculate something. it shows loading cursor. 
only happens in Zbrush profile.

windows 10
amd 5950x w/128g ram
nvidia 3090

blender 3.1.2
mouse look navigation 1.7.8

Thanks.

**Comment by dairin0d** [comment]
I'm afraid this is unavoidable when using the Z-buffer geometry detection method. You can try switching to Raycast or Selection instead, but keep in mind that they have problems with the Sculpt mode.
