### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by CoreyCorza** [dairin0d/blender-2.8-scripts#16]
Still having that problem with extreme lag where there is upto a full second of delay before any pan rotate or zoom starts.
I think we talked last time about it having something to do with the geometry detection?
Seems to be fine in workbench mode but in eevee it's unusable 

https://user-images.githubusercontent.com/40785775/178094240-fac08a16-6b2d-4760-bd89-f66184316316.mp4

**Comment by CoreyCorza** [comment]
https://user-images.githubusercontent.com/40785775/178094357-3bd61a5c-3766-46f5-b45e-51becb25b416.mp4

**Comment by dairin0d** [comment]
Hi, thanks, this could be quite a useful observation!
I made a version that switches the rendering engine to Workbench when trying to get the Z-buffer: [mouselook_navigation.zip](https://github.com/dairin0d/blender-2.8-scripts/files/9078882/mouselook_navigation.zip)
Let me know how it goes :-)

**Comment by CoreyCorza** [comment]
Is meant to actually switch to workbench mode on the user side? 
Either way I'd still have to turn off mouselook to use eevee and physically switch over to my mouse
https://user-images.githubusercontent.com/40785775/178194792-c9ef0fa1-896f-4623-9a4a-b8a2cdf420ab.mp4

**Comment by CoreyCorza** [comment]
Oh! Hang on it does work with rendered mode set to eevee!
Yes!! That is 100% better
https://user-images.githubusercontent.com/40785775/178195851-8ed5ea34-3e25-4267-9861-7cc8dd0c6378.mp4

**Comment by CoreyCorza** [comment]
Also the focus point stopped working in your latest release. When the focus point is on the model it still rotates around the cursor position instead. Do you know whats up with that?

https://user-images.githubusercontent.com/40785775/178196719-29a51357-84b9-44ca-877b-9eb61100f026.mp4

**Comment by dairin0d** [comment]
> Is meant to actually switch to workbench mode on the user side? Either way I'd still have to turn off mouselook to use eevee and physically switch over to my mouse https://user-images.githubusercontent.com/40785775/178194792-c9ef0fa1-896f-4623-9a4a-b8a2cdf420ab.mp4

Oops! Sorry, missed this bug. Here's a (hopefully) fixed version: [mouselook_navigation.zip](https://github.com/dairin0d/blender-2.8-scripts/files/9081224/mouselook_navigation.zip)

**Comment by CoreyCorza** [comment]
Yep thats working great! Cycles is struggling a bit with it but that's not a big deal

**Comment by dairin0d** [comment]
> Also the focus point stopped working in your latest release. When the focus point is on the model it still rotates around the cursor position instead. Do you know whats up with that?

It seems like you have the Auto Depth option enabled in your Navigation preferences:
![image](https://user-images.githubusercontent.com/1641842/178198645-97c380ce-63c6-40c2-b41e-cf528c0b1dea.png)

**Comment by CoreyCorza** [comment]
Ah yep, thanks :)

**Comment by CoreyCorza** [comment]
Getting some weird behavior where the file Ive been using to test on works fine with the new zbuffer trick, but if I start a new file its back to doing the lag thing 
*edit: its actually not working in sculpt mode
https://user-images.githubusercontent.com/40785775/178411340-20278777-f07e-495c-b770-a94fae237802.mp4

**Comment by CoreyCorza** [comment]
Correction: Object mode is fine but it doesnt work in sculpt mode by the looks
https://user-images.githubusercontent.com/40785775/178411929-60344a1c-2401-4748-a11a-5e4471329c4c.mp4

**Comment by CoreyCorza** [comment]
https://user-images.githubusercontent.com/40785775/178412510-063f7110-4683-4059-8013-a8579faf6110.mp4

**Comment by CoreyCorza** [comment]
Another thing I just noticed too is mouselook will stop responding when tabbing back into object mode. Not sure exactly what is causing it but it seems to happen randomly every now and again. Only way to fix it is to uninstall and reinstall mouselook
https://user-images.githubusercontent.com/40785775/178414000-0530e1ef-9760-4c66-92d0-7abf9ecedc5c.mp4

**Comment by dairin0d** [comment]
Thanks again! I think I found a way to make it work in Sculpt mode too: [mouselook_navigation.zip](https://github.com/dairin0d/blender-2.8-scripts/files/9089705/mouselook_navigation.zip)

**Comment by CoreyCorza** [comment]
Perfect!
Uploading YvPv3y3bmT.mp4…

**Comment by dairin0d** [comment]
> Another thing I just noticed too is mouselook will stop responding when tabbing back into object mode. Not sure exactly what is causing it but it seems to happen randomly every now and again. Only way to fix it is to uninstall and reinstall mouselook https://user-images.githubusercontent.com/40785775/178414000-0530e1ef-9760-4c66-92d0-7abf9ecedc5c.mp4

Are there any errors in the system console? I wasn't able to reproduce this issue, so currently have no idea what exactly could be the cause.

**Comment by CoreyCorza** [comment]
I didn't think to check the console but it seems ok now with that last patch. I'll keep that in mind though if it does it again. 
I have plenty of time this afternoon to test more and make sure its all working good. Will report back if anything else pops up. Seems great now though. Nice work!

**Comment by dairin0d** [comment]
Thanks!

**Comment by CoreyCorza** [comment]
Got a few hours in yesterday and no problems.
Absolutely loving mouselook nav atm!!

**Comment by CoreyCorza** [comment]
Still having a little issue with the focus point not latching onto the surface of the mesh. So it rotates around some arbitrary point in the middle of the object. Not a big deal just can't figure out whats causing it. Is there any other settings that might affect that?
https://user-images.githubusercontent.com/40785775/178649522-7de2bce0-e321-499c-b814-04f4ca57c966.mp4

**Comment by CoreyCorza** [comment]
Hmm.. So if I add a new primitive and switch objects then back to the sculpt mesh, it starts working again

https://user-images.githubusercontent.com/40785775/178650665-3200d474-7d44-47fe-ab13-294a6964d13d.mp4

**Comment by CoreyCorza** [comment]
![image](https://user-images.githubusercontent.com/40785775/178650908-241f5428-32e6-4ebe-b85c-215f4a7bd441.png)

**Comment by CoreyCorza** [comment]
Theres no other errors in the console apart from what looks like just a debug print

**Comment by dairin0d** [comment]
> Still having a little issue with the focus point not latching onto the surface of the mesh. So it rotates around some arbitrary point in the middle of the object. Not a big deal just can't figure out whats causing it. Is there any other settings that might affect that?

If you mean the "zoom/rotate around the last sculpted/painted position" feature that Blender has (specifically, the Orbit Around Selection navigation option, when used in a Sculpt or Paint mode) -- unfortunately, it cannot be replicated in an addon (Blender does not expose this information to scripts). The best approximation I can do is use the active object's bounding box center as the rotation point.

**Comment by CoreyCorza** [comment]
Nah. With the focus point in the center of the screen. Sometimes it will lock on to the surface of the mesh and allow me to pivot where that cross hair is. It will detect the surface geo and rotate around that part of the surface.
Example of it working correctly below:


https://user-images.githubusercontent.com/40785775/178732862-d8d13cce-4959-41d4-8929-8eb86bd7b730.mp4

**Comment by CoreyCorza** [comment]
And then sometimes it will just stop detecting the surface of the mesh and start rotating around some arbitrary point inside the mesh, rather than detecting the surface of the mesh where the crosshair is.
Example below of it suddenly changing behavior:

https://user-images.githubusercontent.com/40785775/178733338-908d9bbf-4b67-405f-9be3-9db322bec990.mp4

**Comment by CoreyCorza** [comment]
But it still rotates around the general area that I want anyway. So its not big deal. Just an inconsistant behavior I noticed and was wondering about

**Comment by dairin0d** [comment]
Ah, I see what you mean now. Judging by your videos, you have both Orbit Around Selection and Auto Depth disabled, so the addon is simply rotating around the view origin without any special logic. In LY9B7Xucca.mp4, the view origin was coincidentally near the object's surface, but then you panned the view (and the view origin moved accordingly), so in AuoFo4mi2g.mp4 the view origin was somewhere inside the model.

**Comment by CoreyCorza** [comment]
Ah yep. That makes sense
