### ISSUE TITLE
Can't exit from camera view

### ISSUE THREAD

**Issue by Wolfgang-IX** [dairin0d/blender-2.8-scripts#17]
Hi, I'm not sure if I missed something or if that's how it's, but I can't seem to exit camera view when orbiting like on native.
thanks

![image](https://user-images.githubusercontent.com/47208316/209708710-e2f680e0-ac11-4555-8fc3-c02c2aa57378.png)

**Comment by dairin0d** [comment]
Hi, thanks, there's a new version of the addon published, which hopefully fixes this problem.

**Comment by Wolfgang-IX** [comment]
thank you, it's working now 😁
