### ISSUE TITLE
Zbrush border doesn't show up

### ISSUE THREAD

**Issue by HamedPhixer** [dairin0d/blender-2.8-scripts#18]
Hi. I think it's clear, but the thing is, I'm not sure if I have to have something on or off to make it show up or not. 
I also want to ask that, is this border helps to navigate while there is no space, like when you are in a room or not.
The whole concept is amazing, I was looking for such thing for a long time.

**Comment by dairin0d** [comment]
Hi, thanks, there's a new version of the addon published, which hopefully fixes the "ZBrush border not being drawn" problem.

Yes, ZBrush border is for cases like these, I suppose.
