### ISSUE TITLE
Mouselook Navigation doesn't work when certain tools are active

### ISSUE THREAD

**Issue by Subaphonic** [dairin0d/blender-2.8-scripts#2]
Hi,
Thanks for this amazing tool. I'm experiencing issues with it, it randomly stops functionning (it can be pan, orbit or zoom, depends). It happens especially when closing then reopening a project, and it can happen between layout setups (for instance, in my scene right now it doesn't work in sculpt mode, but in layout mmode it still works). 
If I create a new project it keep working though. 
Thanks for your help

**Comment by dairin0d** [comment]
Hi,
Which version of Blender and what keyconfig preset are you using?
What changes have you made in the addon preferences (if any)?

**Comment by Subaphonic** [comment]
Hey, 
Thanks for your answer. 
I'm on Blender 2.91, using the Zbrush preset. I haven't tweaked anything in the preferences as far as I know (I've tried loading the factory prefs, the issue still occurs). 
I have saved a specific scene in which the MouseLook rotation doesn't work in sculpt mode. I could send it to you if you want?

**Comment by dairin0d** [comment]
Yes, such a scene could be useful. If you prefer it to not be publicly accessible, you can send [me](https://blenderartists.org/u/dairin0d) a private message on blenderartists.

Just to clarify: you tried loading the factory prefs for the whole Blender, then enabled the Mouselook Navigation addon (without any further changes to the preferences), and it consistently doesn't work in the scene you saved?

**Comment by Subaphonic** [comment]
Yes that's what I have done. I have loaded the factory presets, then installed MouseLook Navigation, then applied the Zbrush preset. 
Here is the scene: 

[test_mouselook.zip](https://github.com/dairin0d/blender-2.8-scripts/files/5689481/test_mouselook.zip)

Normally, you should see that the rotation doesn't work in sculpt mode, but works in layout /modeling mode
The position /zoom work for all modes though. 
Many thanks !

**Comment by dairin0d** [comment]
Huh. Turns out, this is due to the currently selected [tool](https://docs.blender.org/manual/en/latest/interface/tool_system.html) taking precedence over all normal operators. Only some tools have this effect ("Edit Face Set", "Annotate" and "Cursor" are among those).

To be honest, I have no idea if it's even possible to make Mouselook Navigation operators have higher priority than tools. It seems that the only solution is to be mindful of the currently selected tool, I guess. ¯\\\_(ツ)\_/¯

**Comment by Subaphonic** [comment]
Uh, that's too bad. Thank you anyways for your help, if you ever find a fix for that issue I'll check on your updates :)
