### ISSUE TITLE
No zooming

### ISSUE THREAD

**Issue by NuKamil** [dairin0d/blender-2.8-scripts#20]
Hey, you probably already know this, but when pressing the ALT key and releasing it, there is no zoom :D

**Comment by dairin0d** [comment]
Hi, sorry for the late response.
When using the ZBrush preset in Mouselook Navigation, you have to first start panning (ALT + LMB drag), then release ALT while still holding LMB to switch to the zoom mode.
Does it not work like this in your case? Or did you expect some other behavior?
I never used ZBrush myself, so this behavior is configured based on the information provided by other people.

**Comment by NuKamil** [comment]
Hey, sorry for the confusion. Now everything works perfectly, just turned off the 3rd mouse button emulation. Thanks for your work, great addon!
👌😊
