### ISSUE TITLE
crosshair showup center when i click left mouse to navigation (zbrush)

### ISSUE THREAD

**Issue by maxryan02** [dairin0d/blender-2.8-scripts#21]
crosshair showup center when i click left mouse to navigation (zbrush)

**Comment by dairin0d** [comment]
Hi, sorry for a late response. Yes, by default the crosshair is visible, you can turn it off in the preferences. Or did you mean something else?
![image](https://github.com/dairin0d/blender-2.8-scripts/assets/1641842/7c101622-fce5-4885-a76c-41bbb83e0ce2)

**Comment by maxryan02** [comment]
Thank you sir.
