### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by NuKamil** [dairin0d/blender-2.8-scripts#22]
Unfortunately it does not work on Blender 4.0.

![blender_s4whoZUOoe](https://github.com/dairin0d/blender-2.8-scripts/assets/42280008/26df809d-d272-48e5-b82e-a41ffc968040)

**Comment by dairin0d** [comment]
Oops! Sorry about that. When I was porting the code to Blender 4.0, I was testing in an earlier build, and forgot to check in the release version. It should be fixed in the 1.8.1 version of the addon (hopefully it will get published within a day).
