### ISSUE TITLE
MouseLook Navigation Problem

### ISSUE THREAD

**Issue by JuanDeSanpe** [dairin0d/blender-2.8-scripts#3]
Hi, I've been using this addon for Blender for a while now and it's great, but there is a function that I can't find or I don't know if it's implemented and I think it would be very useful, the orbit focuses very well on vertices, edges, faces and objects, but in sculpt mode it does not orbit around the last strokes made but around the entire object itself, that is very uncomfortable especially when I want to model more outer parts of a mesh, since it takes the origin as the center of orbit and not the geometry that I am modifying at the moment. Do you know if this option exists? I am currently using version 1.29 and I have used all of them, Blender I have also used the latest versions and it doesn't fix it.

Thanks in advance!

**Comment by dairin0d** [comment]
Sorry for a late response,

This is a known limitation. Unfortunately, Blender does not expose to scripts the information about the last stroke, so such a feature isn't really possible with the existing versions of Blender.

**Comment by JuanDeSanpe** [comment]
Hello good morning, in orbit mode with SHIFT if possible with the last
stroke.

The truth would be a great function to implement, and the addon in if it is
great.

**Comment by ManuelGPz** [comment]
Hello, I am really loving this addon. It is just perfect being able to swap between Zbrush NAvigation when I am sculpting and the Blender one for the rest of the tasks. However, I am trying to set up a hotkey to toggle between both methods. Just a hotkey to turn on and off the addon. For some reason, the Mouselook Nav. toggle doesn't let me add a hotkey by right-clicking on it and there is no option for that on the addon preferences.

I wonder if it would be possible to add this functionality.

Cheers.

**Comment by JuanDeSanpe** [comment]
By the way, all updates are welcome, another thing I wanted to comment on
is the use of the addon when the "DYNTOPO" function is activated, the
sculpting performance drops drastically, unfeasible.

**Comment by dairin0d** [comment]
A new version (1.5.1) was published today (see https://blenderartists.org/t/mouselook-navigation-addon-zbrush-mode/629567/200 for more details). In particular, it's now possible to assign a shortcut for the "Enable/Disable Mouselook Navigation" toggle, and to disable raycasting (the primary cause of addon's bad performance in Sculpt mode).

**Comment by ManuelGPz** [comment]
Hello,
I have found an issue with the new version. 

I am using the Zbrush preset on it. When I have different facets on my model, and I use the Automasking by Facesets feature, Blender just let work with one and only one of the presets. If I try to work over any other of the facets it just doesn't work. It only let me work with the first facet I touched and got a stick on if for the time being. That auto masking by face set functionally unusable.

I think there might be an issue with how Blender determinates what was the last vertex select.

Thank you.

**Comment by dairin0d** [comment]
Er... please create new issues for problems not related to the current issue ;-)
Just in case, I created a new issue from your last comment: https://github.com/dairin0d/blender-2.8-scripts/issues/4

**Comment by ManuelGPz** [comment]
> Er... please create new issues for problems not related to the current issue ;-)
> Just in case, I created a new issue from your last comment: #4

Thanks for that.

I will keep it in mind for the next time.

Apologies and thank you again.
