### ISSUE TITLE
Mouselook Navigation: Automasking by Facesets

### ISSUE THREAD

**Issue by dairin0d** [dairin0d/blender-2.8-scripts#4]
Report by @ManuelGPz:

I am using the Zbrush preset on it. When I have different facets on my model, and I use the Automasking by Facesets feature, Blender just let work with one and only one of the presets. If I try to work over any other of the facets it just doesn't work. It only let me work with the first facet I touched and got a stick on if for the time being. That auto masking by face set functionally unusable.

I think there might be an issue with how Blender determines what was the last vertex select.

_Originally posted by @ManuelGPz in https://github.com/dairin0d/blender-2.8-scripts/issues/3#issuecomment-778687387_

**Comment by dairin0d** [comment]
@ManuelGPz, I don't seem to be able to reproduce this problem. Can you provide a video of how exactly to reproduce it, or a .blend file in which the problem reliably appears?
By the way, which version of Blender are you using?

**Comment by ManuelGPz** [comment]
Using Blender 2.91

Let me do the video for you and upload it.

**Comment by ManuelGPz** [comment]
Thanks for your fast answer, and please let me know if the GIF video is not clear enough.

You can see how with the Blender preset at first, the automasking works well.
Then with Zbrush preset, it doesn't work and it doesn't allow me to grab from the grey faceset. 
After that, I turn off the addon to show how it works just fine again when the MouseLookNavigation Addon is off.


[
![FaceSetsProblem_001](https://user-images.githubusercontent.com/58131591/107864004-77e72780-6eac-11eb-85cf-9db1d3541166.gif)
](url)

**Comment by dairin0d** [comment]
Thanks! I'll try to investigate that.

**Comment by ManuelGPz** [comment]
Thank you :)

**Comment by dairin0d** [comment]
Hi, in the recent addon update (1.6.0) I added the Z-buffer geometry detection method, which doesn't have these issues.
For other geometry detection methods, such problems are impossible to avoid, so Z-buffer is the default method now.

**Comment by ManuelGPz** [comment]
Works perfectly! Thanks so much for that.
