### ISSUE TITLE
Severe "slowdowns"

### ISSUE THREAD

**Issue by CoreyCorza** [dairin0d/blender-2.8-scripts#5]
To avoid slowdowns, disable the "Record Z-buffer" option in the addon's preferences

Can't find any option to disable the "record zbuffer" option as mentioned in documentation to avoid slowdowns.

Getting severe lag when enabling mouselook navigation and using mouslook navigation.
No lag when using blenders native navigations.
Turn on mouselook, severe lag upto 1 sec.
Turn off mouselook, no lag.
Turn on mouselook, heaps of lag.
Turn off mousleook, no lag

**Comment by CoreyCorza** [comment]
Mouselook on: Laggy
![ZcsgTgNndE](https://user-images.githubusercontent.com/40785775/107997449-7cd3e480-702e-11eb-8e5f-a0cf4ce8cfc1.gif)
Mouselook off: Not laggy
![MufX7xePui](https://user-images.githubusercontent.com/40785775/107997498-970dc280-702e-11eb-8a80-85d2b4b84062.gif)

**Comment by CoreyCorza** [comment]
More info-
My specs: AMD 3700x, 32gb, Geforce 3060ti, WIN10
Mouselook versions exhibiting the problem: v1.51, v1.50 v1.41 (havent used anything older than that)
Blender versions used: 2.91.2. 2.92

**Comment by dairin0d** [comment]
Hi, sorry for a late response,
Unfortunately, I haven't updated the documentation in quite a while. The Record Z-buffer option has been removed when I ported the addon to Blender 2.8, so lag must be due to something else. I'll try to investigate this, but it may take quite a while.

**Comment by dairin0d** [comment]
Hi, in the recent addon release (1.6.0) I added back the Z-buffer geometry detection method. Can you check if it solves/alleviates the lag/slowdown problem?

As for documentation, I haven't yet been able to update it, unfortunately... Hopefully I'll finish it sometime this week.

**Comment by CoreyCorza** [comment]
Loaded up v1.6.0 and its all working smoothly now, all on default settings.
Perfect!

**Comment by CoreyCorza** [comment]
Sorry to be a pain in the ass but..  problem is persisting with dyntopo activated. Didn't notice until now. Even on zbuffer with a low poly count :'(

https://user-images.githubusercontent.com/40785775/109497101-46da3a00-7add-11eb-89a0-3b182c579176.mp4

**Comment by dairin0d** [comment]
Thanks! I forgot about the dyntopo, sorry :-(

I've committed a fixed version to the github just now. If you don't want to wait for an updated zip on gumroad (another person handles those), you can manually replace the `__init__.py` in the addon's folder with https://github.com/dairin0d/blender-2.8-scripts/blob/master/scripts/addons/mouselook_navigation/__init__.py

**Comment by CoreyCorza** [comment]
Thank you!!
