### ISSUE TITLE
Feature Request: Zbrush style navigation in node/graph editors?

### ISSUE THREAD

**Issue by ghost** [dairin0d/blender-2.8-scripts#6]
Is there currently any way to set up zbrush style navigation (alt+LMB pan/zoom) on node/graph editors? 

Swapping back and forth between the default and zbrush navigation styles depending on context is a little jarring. Especially if you only want to make a small tweak a material and swapping back to mouse takes more time than the change!

Great add-on by the way! You're on my to-buy list. You deserve a few coffees or something stronger for your fine work <3

**Comment by dairin0d** [comment]
Currently, the addon implements only navigation in 3D view. Making an implementation for the node editor (and, perhaps other 2D views) certainly seems possible, but developing such a feature would take a significant chunk of time... Even if I eventually get around to do it, it won't be anytime soon.

That said, you can try to set up Blender's 2D view navigation keymaps and Mouselook Navigation shortcuts to use the same key combinations. It won't be exactly as in ZBrush, but you at least can make them consistent. For example, using Alt+LMB (Click Drag event) for Pan, and Alt+LMB (Click event) for Zoom.

**Comment by ghost** [comment]
Ah, I'm a moron. Your solution is perfect. Thank you.
