### ISSUE TITLE
MouseLook On/Off Toogle shortcut

### ISSUE THREAD

**Issue by ManuelGPz** [dairin0d/blender-2.8-scripts#7]
Thanks so much for the last update. It is great being able to work with facesets among other things.

However, I have noticed that the option to assign a shortcut to the MouseLook On/Off Toggle is not available anymore. Personally, I found it really usefull.
Is it available within the Addon options? Maybe it has been moved there but I couldn't find it so far.

Thanks so much.

**Comment by dairin0d** [comment]
Oops! That's a regression. I forgot about this when I was making various internal changes.
I'll try to fix it this week.

**Comment by ManuelGPz** [comment]
Thanks so much for that.
Really appreciate it 🙇‍♂️

**Comment by dairin0d** [comment]
Well, I happen to have fixed this just now, actually :-)

**Comment by ManuelGPz** [comment]
Same release? 
I will download first thing tomorrow morning 💪🏼

It's already midnight in Melbourne 😅😅

Thanks so much for that. Appreciate it.
You are awesome man!🙇‍♂️

**Comment by dairin0d** [comment]
Yeah, the 1.6.1 version 🙂

**Comment by ManuelGPz** [comment]
Will be my breakfast in 6 hours :)

Thanks again :)

**Comment by ManuelGPz** [comment]
Is it available to download? I usually access it via Gumroad.

**Comment by dairin0d** [comment]
I haven't heard from the guy who manages the Gumroad, so probably not yet. Doesn't Gumroad send notifications about updates, by the way?

**Comment by ManuelGPz** [comment]
Yeah, you are right. They usually send a notification. They haven't sent anything yet.
Sorry I didn't mean to rush you at all. Just confirming if that would be the way to access the new release, or if the access was via Github.

Thanks so much again :)

**Comment by dairin0d** [comment]
This fix (along with some others) should now be on gumroad.

**Comment by ManuelGPz** [comment]
Thank you :)
