### ISSUE TITLE
Mouselook Navigation 1.62

### ISSUE THREAD

**Issue by visualworx** [dairin0d/blender-2.8-scripts#8]
Firstly, thanks for the great addon.

Secondly, I got two issues on 1.62 version.

  1. zip folder hierarchy
      - it has two depths. there's one more "mouselook navigation" folder inside of "mouselook navigation folder in the zip folder sorry for my poor English. Because of this the normal zip folder installation method is not working properly. It can be easily fixed though.
  2. No presets option loaded on 1.62
      - not sure why.
  
None of the above happens on 1.60 version. Thanks

**Comment by dairin0d** [comment]
Thanks! I kind of forgot that the zip on Gumroad is not exactly the same as the one I have locally. The person who manages the Gumroad adds a readme pdf and an image with the list of changes to each published zip, so mistakes like this can sometimes happen.

He uploaded a fixed zip, it should install properly now. If there are still problems with presets, let me know :-)

**Comment by visualworx** [comment]
Thanks a lot for the quick response. I appreciate it. I'll test it out soon and let you know if the preset issue still happens. :)

**Comment by visualworx** [comment]
Hello there, I think the focal point isn't working as I expected if the origin of the mesh is out of center.

![image](https://user-images.githubusercontent.com/54339099/119696830-8a4d0600-be8a-11eb-9c0f-2cb58b718f28.png)

1. add cube
2. move the origin far from its center
3. go to sculpt / object mode (or nothing selected in edit mode)
4. rotate the viewport

what I expected is the viewport rotation point should be center of the screen. If I turn off the addon it works well.
thanks!

**Comment by dairin0d** [comment]
This seems to be unrelated to the original issue. I created a [new issue](https://github.com/dairin0d/blender-2.8-scripts/issues/9) from your comment, its discussion should continue there.
In the future, please open a separate issue for each separate problem / request (unless the same thing was already reported by someone else) :-)

**Comment by visualworx** [comment]
Sorry about that. I won't do this again. Thanks.
