### ISSUE TITLE
Mouselook Navigation: different from Blender behavior when Orbit Around Selection is enabled

### ISSUE THREAD

**Issue by dairin0d** [dairin0d/blender-2.8-scripts#9]
Hello there, I think the focal point isn't working as I expected if the origin of the mesh is out of center.

![image](https://user-images.githubusercontent.com/54339099/119696830-8a4d0600-be8a-11eb-9c0f-2cb58b718f28.png)

1. add cube
2. move the origin far from its center
3. go to sculpt / object mode (or nothing selected in edit mode)
4. rotate the viewport

what I expected is the viewport rotation point should be center of the screen. If I turn off the addon it works well.
thanks!

_Originally posted by @visualworx in https://github.com/dairin0d/blender-2.8-scripts/issues/8#issuecomment-848923336_

**Comment by dairin0d** [comment]
@visualworx I'm afraid I don't have enough information to understand the problem. I have performed the steps you described (with factory settings both in Blender and in the addon), and the viewport rotation point stays at the center of the screen at all times.
Just in case, which version of Blender are you using? I tested in 2.80 and 2.92.

**Comment by visualworx** [comment]
Hmm. I will try the addon reset and update the issue. Again, thanks for the instant feedback.

**Comment by visualworx** [comment]
![image](https://user-images.githubusercontent.com/54339099/119748517-0584db00-bed0-11eb-9b72-65750b4d18d2.png)
My bad. The issue was the option called "orbit around selection". As default it turned off. however, the other blender native navigation like middle click rotation works well without any issue like this.

**Comment by dairin0d** [comment]
Hmm, with Orbit Around Selection, there are several different scenarios:
- In Object mode, Blender orbits around the average of the bounding box centers of the selected object(s). If nothing is selected, the view orbits around the last orbit position.
- In Edit mode, Blender orbits around the average of the selected vertices. If nothing is selected, the view orbits around the last orbit position.
- In Sculpt mode, Blender orbits around the last stroke position.

Currently, the addon orbits around the average of the origins of the selected object(s) / vertices. If nothing is selected, the view will orbit around its default focus point.
I can use the average of the bounding box centers for Object mode, and remember the last orbit position. However, there's not much I can do in Sculpt mode (python scripts have no access to the last stroke position), aside from using the bounding box center at the moment the Sculpt mode was entered.

**Comment by visualworx** [comment]
Thanks for the detailed feedback. It is totally fine with current settings. I was just wondering why Blender's navigation method works differently with that option turned on compared to mouse look navigations. 

Thanks again for the great addon!

**Comment by dairin0d** [comment]
So... should I change anything, or the issue can be considered closed?
